// This file was generated by the FlutterFire CLI command.
// flutter packages pub run build_runner build
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY', defaultValue: 'your-web-api-key-here'),
    appId: String.fromEnvironment('FIREBASE_WEB_APP_ID', defaultValue: '1:623746770431:web:f266dc8a23a4c95c5773ca'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID', defaultValue: '623746770431'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID', defaultValue: 'timewarden-b426f'),
    authDomain: String.fromEnvironment('FIREBASE_AUTH_DOMAIN', defaultValue: 'timewarden-b426f.firebaseapp.com'),
    storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET', defaultValue: 'timewarden-b426f.firebasestorage.app'),
    measurementId: String.fromEnvironment('FIREBASE_MEASUREMENT_ID', defaultValue: 'G-NTV5F3MPQC'),
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY', defaultValue: 'your-android-api-key-here'),
    appId: String.fromEnvironment('FIREBASE_ANDROID_APP_ID', defaultValue: '1:623746770431:android:91dfdde24b2bd8955773ca'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID', defaultValue: '623746770431'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID', defaultValue: 'timewarden-b426f'),
    storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET', defaultValue: 'timewarden-b426f.firebasestorage.app'),
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY', defaultValue: 'your-ios-api-key-here'),
    appId: String.fromEnvironment('FIREBASE_IOS_APP_ID', defaultValue: '1:623746770431:ios:91dfdde24b2bd8955773ca'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID', defaultValue: '623746770431'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID', defaultValue: 'timewarden-b426f'),
    storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET', defaultValue: 'timewarden-b426f.firebasestorage.app'),
    iosClientId: String.fromEnvironment('FIREBASE_IOS_CLIENT_ID', defaultValue: 'your-ios-client-id-here'),
    iosBundleId: String.fromEnvironment('FIREBASE_IOS_BUNDLE_ID', defaultValue: 'com.timewarden.app'),
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_MACOS_API_KEY', defaultValue: 'your-macos-api-key-here'),
    appId: String.fromEnvironment('FIREBASE_MACOS_APP_ID', defaultValue: '1:623746770431:macos:91dfdde24b2bd8955773ca'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID', defaultValue: '623746770431'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID', defaultValue: 'timewarden-b426f'),
    storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET', defaultValue: 'timewarden-b426f.firebasestorage.app'),
    iosClientId: String.fromEnvironment('FIREBASE_MACOS_CLIENT_ID', defaultValue: 'your-macos-client-id-here'),
    iosBundleId: String.fromEnvironment('FIREBASE_MACOS_BUNDLE_ID', defaultValue: 'com.timewarden.app'),
  );
}
